// contextBridge: the ONLY surface the renderer can reach. Mirrors main/ipc.ts.

import { contextBridge, ipcRenderer } from "electron";

const call = (channel: string) => (...args: unknown[]) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld("pos", {
  people: {
    list: call("people.list"),
    get: call("people.get"),
    patch: call("people.patch"),
    patchWithExtract: call("people.patchWithExtract"),
    merge: call("people.merge"),
    delete: call("people.delete"),
    reconnect: call("people.reconnect"),
    dismissReconnect: call("people.dismissReconnect"),
    undismissReconnect: call("people.undismissReconnect"),
    exportCsv: call("people.exportCsv"),
  },
  query: { rank: call("query.rank") },
  review: {
    pending: call("review.pending"),
    keep: call("review.keep"),
    discard: call("review.discard"),
    group: call("review.group"),
    mergeCluster: call("review.mergeCluster"),
    dismissDuplicates: call("review.dismissDuplicates"),
    resolveAmbiguous: call("review.resolveAmbiguous"),
    dismissAmbiguous: call("review.dismissAmbiguous"),
  },
  groups: {
    list: call("groups.list"),
    create: call("groups.create"),
    rename: call("groups.rename"),
    delete: call("groups.delete"),
    assign: call("groups.assign"),
    assignMany: call("groups.assignMany"),
    remove: call("groups.remove"),
    hide: call("groups.hide"),
    hideContacts: call("groups.hideContacts"),
    suppressFollowUps: call("groups.suppressFollowUps"),
  },
  commitments: {
    list: call("commitments.list"),
    schedule: call("commitments.schedule"),
    updateText: call("commitments.updateText"),
    confirm: call("commitments.confirm"),
    drop: call("commitments.drop"),
    toTask: call("commitments.toTask"),
    toEvent: call("commitments.toEvent"),
  },
  tasks: {
    braindump: call("tasks.braindump"),
    list: call("tasks.list"),
    setStatus: call("tasks.setStatus"),
  },
  plan: {
    generate: call("plan.generate"),
    get: call("plan.get"),
    accept: call("plan.accept"),
    push: call("plan.push"),
  },
  outcomes: {
    needed: call("outcomes.needed"),
    capture: call("outcomes.capture"),
    adherence: call("outcomes.adherence"),
  },
  sync: {
    run: call("sync.run"),
    status: call("sync.status"),
    embed: call("sync.embed"),
    pickAndRun: call("sync.pickAndRun"),
  },
  mail: {
    list: call("mail.accounts.list"),
    add: call("mail.accounts.add"),
    remove: call("mail.accounts.remove"),
    connectOAuth: call("mail.connectOAuth"),
  },
  gcal: {
    connect: call("gcal.connect"),
    cancel: call("gcal.cancel"),
    connected: call("gcal.connected"),
    scopeStatus: call("gcal.scopeStatus"),
    reconcile: call("gcal.reconcile"),
    events: call("gcal.events"),
  },
  ics: { list: call("ics.list"), add: call("ics.add"), remove: call("ics.remove") },
  notion: {
    available: call("notion.available"),
    targets: call("notion.targets"),
    setParent: call("notion.setParent"),
    sync: call("notion.sync"),
  },
  applecal: {
    available: call("applecal.available"),
    calendars: call("applecal.calendars"),
    events: call("applecal.events"),
    mirror: call("applecal.mirror"),
  },
  settings: {
    keys: call("settings.keys"),
    setKey: call("settings.setKey"),
    doctrineGet: call("settings.doctrine.get"),
    doctrineSet: call("settings.doctrine.set"),
    spend: call("settings.spend"),
    setCeiling: call("settings.setCeiling"),
    get: call("settings.get"),
    set: call("settings.set"),
  },
  msgplans: { run: call("msgplans.run"), list: call("msgplans.list") },
  digest: { send: call("digest.send"), preview: call("digest.preview") },
  capture: { senders: call("capture.senders") },
  undo: { do: call("undo.do"), redo: call("undo.redo") },
  worklog: { list: call("worklog.list"), add: call("worklog.add"), catchUp: call("worklog.catchUp") },
  context: {
    list: call("context.list"),
    set: call("context.set"),
    delete: call("context.delete"),
    resolveDate: call("context.resolveDate"),
  },
  prefs: { get: call("prefs.get"), set: call("prefs.set"), reveal: call("prefs.reveal") },
  assistant: { command: call("assistant.command") },
  stt: { transcribe: call("stt.transcribe") },
  inbox: {
    list: call("inbox.list"),
    sendEmail: call("inbox.sendEmail"),
    sendIMessage: call("inbox.sendIMessage"),
    sendIMessageChat: call("inbox.sendIMessageChat"),
    handles: call("inbox.handles"),
  },
  drafts: { list: call("drafts.list"), generate: call("drafts.generate"), setStatus: call("drafts.setStatus") },
  voice: { synthesize: call("voice.synthesize"), get: call("voice.get") },
  app: { openFullDiskAccess: call("app.openFullDiskAccess"), openLinkedIn: call("app.openLinkedIn") },
});
